Spice/Spice/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }
        // Get index of all coupons
        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupon.ToListAsync());
        }
        // Get create
        public IActionResult Create()
        {
            return View();
        }
        // Post create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupons)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using(var fs1 = files[0].OpenReadStream())
                    {
                        using(var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    coupons.Picture = p1;
                }
                else
                {
                    return View(coupons);
                }
                _db.Coupon.Add(coupons);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupons);
        }

        // Get Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Coupon coupon = await _db.Coupon.FirstOrDefaultAsync(c => c.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }
        // Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Coupon coupon)
        {
            if (id == null)
            {
                return NotFound();
            }
            // we need AsNoTracking here to prevent tracking errors
            var couponFromDb = await _db.Coupon.AsNoTracking().FirstOrDefaultAsync(c => c.Id == id);
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using(var fs1 = files[0].OpenReadStream())
                    {
                        using(var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    coupon.Picture = p1;
                }
                else
                {
                    if (couponFromDb.Picture != null)
                    {
                        coupon.Picture = couponFromDb.Picture;
                    }
                    else
                    {
                        return View(coupon);
                    }
                }
                _db.Coupon.Update(coupon);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(coupon);
        }
        // Get Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Coupon coupon = await _db.Coupon.FirstOrDefaultAsync(c => c.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        //Get Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Coupon coupon = await _db.Coupon.FirstOrDefaultAsync(c => c.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        // Post delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Coupon coupon = await _db.Coupon.FirstOrDefaultAsync(c => c.Id == id);

            if (coupon == null)
            {
                return NotFound();
            }

            _db.Coupon.Remove(coupon);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Spice/Spice/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            // Ingelogde gebruiker op halen
            var claimsIdentity = (ClaimsIdentity) this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Unlock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now;
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Spice/Spice/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success" form-control>Back to list</a>
    </div>
</div>

Spice/Spice/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> Create New</a>
</p>

Spice/Spice/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Spice/Views/Shared/_DetailsAndBackToListButton.cshtml
@model  int

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" class="btn btn-success form-control" asp-route-id="@Model">Edit</a>

    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Spice/Views/Shared/_EditAndBackToListButton.cshtml
@model  int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Spice/Views/Shared/_IndividualOrderDetals.cshtml
@model Spice.Models.ViewModels.OrderDetailsViewModel
@using Spice.Utility

<form asp-action="OrderPickup" asp-controller="Order" asp-route-OrderId=@Model.OrderHeader.Id method="POST">
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100;">
        <div class="col-lg-8 col-12" style="border-right:1px solid bbb9b9;">
            <br />
            <input type="hidden" asp-for="OrderHeader.Id" />
            <div class="form-group row">
                <div class="col-3">
                    <Label asp-for="OrderHeader.PickupName"></Label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <Label asp-for="OrderHeader.ApplicationUser.Email"></Label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <Label asp-for="OrderHeader.ApplicationUser.PhoneNumber"></Label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <Label asp-for="OrderHeader.OrderTotal"></Label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <Label asp-for="OrderHeader.OrderDate"></Label>
                </div>
                <div class="col-9">
                    <input
                        value="@Model.OrderHeader.PickupDate.ToShortDateString() @Model.OrderHeader.PickupDate.ToShortTimeString()"
                        disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <Label asp-for="OrderHeader.Comments"></Label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">Order ID: </span>
                <span class="badge badge-secondary badge-pill">@Model.OrderHeader.Id</span>
            </h4>
            <ul class="list-group mb-3">
                @{ var total = 0.0;}
                @foreach (var details in Model.OrderDetails)
                {
                <li class="list-group-item d-flex justify-content-between">
                    <div>
                        <h6 class="my-0">@details.Name</h6>
                        <small class="text-muted">Quantity: @details.Count</small>
                    </div>
                    <span class="text-muted">$ @(details.Price * details.Count)</span>
                    @{total += (details.Price * details.Count);}
                </li>
                }
                @if(Model.OrderHeader.CouponCode != null)
                {
                <li class="list-group-item d-flex justify-content-between">
                    <div class="text-success">
                        <h6 class="my-0">Promo code</h6>
                        <small>@Model.OrderHeader.CouponCode</small>
                    </div>
                    <span class="text-success">- $ @(total - Model.OrderHeader.OrderTotal)</span>
                </li>
                }
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info">Total amount: </span>
                    <strong class="text-info">$ @Model.OrderHeader.OrderTotal</strong>
                </li>
            </ul>
            @if(Model.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser)))
            {
            <button type="submit" class="btn btn-success form-control" ><i class="far fa-thumbs-up"></i>&nbsp;Confirm pickup</button>
            }
            else
            {
            <p class="btn btn-info form-control">@Model.OrderHeader.Status</p>
            }
        </div>
    </div>
</form>

Spice/Spice/Views/Shared/_Layout.cshtml
@using Spice.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />

</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/mild.png">
                    <img src="~/images/spicy.png">
                    <img src="~/images/veryspicy.png">
                    <label class="text-info" style="cursor:pointer;">Spice</label>
                    </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.IsInRole(SD.ManagerUser))
                        {
                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">SubCategory</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">Menu Item</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupon</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">User</a>
                            </div>
                        </li>
                        }

                        @if(User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.CustomerEndUser) || User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser))
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory"
                                    class="nav-link">
                                    Order History
                                </a>
                            </li>
                        }
                        @if(User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser))
                        {
                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Order Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                @if(User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser)){
                                <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order" asp-area="Customer">Manage Order</a>   
                                }
                                @if(User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.ManagerUser)){
                                <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Order" asp-area="Customer">Order Pickup</a>
                                }                                
                            </div>
                        </li>
                        }                        

                        @if(HttpContextAccessor.HttpContext.Session.GetInt32(SD.sessionShoppingCartCount) != null)
                        {
                        <li style="color:white;">
                        <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                            @{
                                var count = HttpContextAccessor.HttpContext.Session.GetInt32(SD.sessionShoppingCartCount);
                            }
                                <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                            </a>
                        </li>
                        }else
                        {
                        <li style="color:white;">
                            <a href="#" class="nav-link"><i class="fas fa-shopping-cart"></i> &nbsp; (0)</a>
                        </li>
                        }

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color:#343a40;">
        <div class="container">
            &copy; 2019 - Spice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/04x6x8sknn7gkjwg2ljp5odc0qam0pc9u4n720my2tqefcoj/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://kit.fontawesome.com/0610a5b886.js" crossorigin="anonymous"></script>
    <script src="~/js/jquery-ui.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Spice/Spice/Views/Shared/_OrderStatus.cshtml
@model Spice.Models.ViewModels.OrderDetailsViewModel
@using Spice.Utility
<div class="card">
  <div class="card-header">
    Order Status
  </div>
  <div class="card-body">
      @if(Model.OrderHeader.Status == SD.StatusSubmitted)
      {
          <img src="@SD.ImageOrderPlaced" class="container"/>
      }
            @if(Model.OrderHeader.Status == SD.StatusInProcess)
      {
          <img src="@SD.ImageOrderInKitchen"/>
      }
            @if(Model.OrderHeader.Status == SD.StatusReady)
      {
          <img src="@SD.ImageOrderReadyForPickup"/>
      }
            @if(Model.OrderHeader.Status == SD.StatusCompleted)
      {
          <img src="@SD.ImageOrderCompleted"/>
      }
  </div>
</div>

Spice/Spice/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Spice/Spice/Views/Shared/_TableButtonPartial.cshtml
@model int  

<td style="width:30px;">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model"><i class="fas fa-edit"></i></a>
        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model"><i class="fas fa-list-alt"></i></a>
        <a class="btn btn-warning text-white" asp-action="Delete" asp-route-Id="@Model"><i class="fas fa-trash-alt"></i></a>
    </div>
</td>

Spice/Spice/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>

@if(Model.Count() > 0 )
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>
        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px;">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px; border:1px solid #bbb9b9"/>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon;">@item.Name</label>
                                @if(item.Spicyness == "1")
                                {
                                    <img src="/images/mild.png" title="Mild"/>
                                }
                                 @if(item.Spicyness == "2")
                                {
                                    <img src="/images/spicy.png" title="Spicy"/>
                                }
                                @if(item.Spicyness == "3")
                                {
                                    <img src="/images/verySpicy.png" title="Very Spicy"/>
                                }                                                               
                            </div>
                            <div class="col-4 text-right" style="color:maroon;">
                                <h4>$@item.Price</h4>
                            </div>
                        </div>
                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Details</a>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="p-4"></div>
    </div>
}